/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'donation-settings': DonationSetting;
    'anchor-day': AnchorDay;
    dropdowns: Dropdown;
    integrations: Integration;
    forms: Form;
    'cookie-consent': CookieConsent;
    'coming-soon': ComingSoon;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'donation-settings': DonationSettingsSelect<false> | DonationSettingsSelect<true>;
    'anchor-day': AnchorDaySelect<false> | AnchorDaySelect<true>;
    dropdowns: DropdownsSelect<false> | DropdownsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'cookie-consent': CookieConsentSelect<false> | CookieConsentSelect<true>;
    'coming-soon': ComingSoonSelect<false> | ComingSoonSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Line breaks are kept.
   */
  brandTitle?: string | null;
  navItems?:
    | {
        label: string;
        /**
         * A path such as /about, a full URL, or a mailto: link.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The Donate button in the header.
   */
  donateLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The cookie settings link is added after these; its label is on Cookie Consent.
   */
  links?:
    | {
        label: string;
        /**
         * A path such as /about, a full URL, or a mailto: link.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  legalText?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-settings".
 */
export interface DonationSetting {
  id: number;
  suggestedAmounts?:
    | {
        /**
         * In cents: 2500 is $25.00.
         */
        amount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Three-letter ISO code in lower case, as Stripe expects.
   */
  currency?: string | null;
  allowCustomAmount?: boolean | null;
  /**
   * Smallest custom amount. In cents: 2500 is $25.00.
   */
  minimumAmount?: number | null;
  /**
   * Copy on /donate.
   */
  page?: {
    kicker?: string | null;
    heading?: string | null;
    lead?: string | null;
    reasonsHeading?: string | null;
    reasons?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
    amountLegend?: string | null;
    /**
     * The "Other" amount option.
     */
    otherLabel?: string | null;
    /**
     * Label on the custom amount input.
     */
    otherAmountLabel?: string | null;
    /**
     * Hint under the custom amount input. Use {minimum} for the minimum amount.
     */
    otherAmountHint?: string | null;
    submitLabel?: string | null;
    securePaymentNote?: string | null;
    /**
     * Shown when no valid amount is chosen. Use {minimum} for the minimum amount.
     */
    errorText?: string | null;
  };
  /**
   * Line above the heading. Use {amount} for the amount given.
   */
  thankYouKicker?: string | null;
  thankYouHeading?: string | null;
  thankYouBody?: string | null;
  thankYouLinkLabel?: string | null;
  /**
   * Shown when Stripe has not confirmed the payment.
   */
  unconfirmedHeading?: string | null;
  unconfirmedBody?: string | null;
  unconfirmedLinkLabel?: string | null;
  /**
   * Copy shown by every Donate banner block.
   */
  banner?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Button label.
     */
    label?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every field is optional while the details are being confirmed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anchor-day".
 */
export interface AnchorDay {
  id: number;
  date?: string | null;
  venue?: string | null;
  moderator?: string | null;
  mc?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dropdowns".
 */
export interface Dropdown {
  id: number;
  territories?:
    | {
        label: string;
        /**
         * Stored on submissions and sent to Airtable. Avoid changing it once in use.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  audienceTypes?:
    | {
        label: string;
        /**
         * Stored on submissions and sent to Airtable. Avoid changing it once in use.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        label: string;
        /**
         * Stored on submissions and sent to Airtable. Avoid changing it once in use.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  /**
   * For example GTM-ABC1234.
   */
  gtmContainerId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * One entry per form, shown on /thank-you/<form> after it is sent.
   */
  thankYou?:
    | {
        form: 'register-interest' | 'cta-consultation' | 'partner' | 'relay' | 'contact';
        heading: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consent".
 */
export interface CookieConsent {
  id: number;
  heading?: string | null;
  body?: string | null;
  acceptLabel?: string | null;
  rejectLabel?: string | null;
  /**
   * The footer link that reopens the cookie banner.
   */
  settingsLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon".
 */
export interface ComingSoon {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Line breaks are kept.
   */
  brandTitle?: string | null;
  /**
   * Small uppercase line above the headline.
   */
  kicker?: string | null;
  /**
   * Line breaks are kept.
   */
  headline: string;
  lead?: string | null;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * The QR code is generated from this link.
     */
    url?: string | null;
  };
  qr?: {
    label?: string | null;
    sublabel?: string | null;
  };
  details?:
    | {
        icon?: ('calendar' | 'map-pin' | 'globe' | 'users' | 'clock' | 'mail') | null;
        title: string;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as a slow crossfade, 8 seconds each. Set the focal point on each image to control cropping.
   */
  backgroundImages?: (number | Media)[] | null;
  footerLeft?: string | null;
  footerRight?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  brandTitle?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  donateLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  tagline?: T;
  legalText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-settings_select".
 */
export interface DonationSettingsSelect<T extends boolean = true> {
  suggestedAmounts?:
    | T
    | {
        amount?: T;
        id?: T;
      };
  currency?: T;
  allowCustomAmount?: T;
  minimumAmount?: T;
  page?:
    | T
    | {
        kicker?: T;
        heading?: T;
        lead?: T;
        reasonsHeading?: T;
        reasons?:
          | T
          | {
              text?: T;
              id?: T;
            };
        note?: T;
        amountLegend?: T;
        otherLabel?: T;
        otherAmountLabel?: T;
        otherAmountHint?: T;
        submitLabel?: T;
        securePaymentNote?: T;
        errorText?: T;
      };
  thankYouKicker?: T;
  thankYouHeading?: T;
  thankYouBody?: T;
  thankYouLinkLabel?: T;
  unconfirmedHeading?: T;
  unconfirmedBody?: T;
  unconfirmedLinkLabel?: T;
  banner?:
    | T
    | {
        heading?: T;
        body?: T;
        label?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anchor-day_select".
 */
export interface AnchorDaySelect<T extends boolean = true> {
  date?: T;
  venue?: T;
  moderator?: T;
  mc?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dropdowns_select".
 */
export interface DropdownsSelect<T extends boolean = true> {
  territories?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  audienceTypes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  gtmContainerId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  thankYou?:
    | T
    | {
        form?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consent_select".
 */
export interface CookieConsentSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  acceptLabel?: T;
  rejectLabel?: T;
  settingsLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon_select".
 */
export interface ComingSoonSelect<T extends boolean = true> {
  logo?: T;
  brandTitle?: T;
  kicker?: T;
  headline?: T;
  lead?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  qr?:
    | T
    | {
        label?: T;
        sublabel?: T;
      };
  details?:
    | T
    | {
        icon?: T;
        title?: T;
        subtitle?: T;
        id?: T;
      };
  backgroundImages?: T;
  footerLeft?: T;
  footerRight?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}