/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    news: News;
    partners: Partner;
    supporters: Supporter;
    faqs: Faq;
    'form-submissions': FormSubmission;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    supporters: SupportersSelect<false> | SupportersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'donation-settings': DonationSetting;
    'anchor-day': AnchorDay;
    dropdowns: Dropdown;
    integrations: Integration;
    forms: Form;
    'cookie-consent': CookieConsent;
    'coming-soon': ComingSoon;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'donation-settings': DonationSettingsSelect<false> | DonationSettingsSelect<true>;
    'anchor-day': AnchorDaySelect<false> | AnchorDaySelect<true>;
    dropdowns: DropdownsSelect<false> | DropdownsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'cookie-consent': CookieConsentSelect<false> | CookieConsentSelect<true>;
    'coming-soon': ComingSoonSelect<false> | ComingSoonSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The page with slug "home" is the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Generated from the title when left empty.
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | StatementBlock
        | HostMapBlock
        | SummitWeekBlock
        | RoadmapBlock
        | FlowBlock
        | CardGridBlock
        | ActionAreasBlock
        | SupporterLevelsBlock
        | LogoGridBlock
        | FaqListBlock
        | NewsTeaserBlock
        | DonateBannerBlock
        | FormBlock
        | AnchorDayBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  style: 'map' | 'photo' | 'plain';
  kicker?: string | null;
  /**
   * Line breaks are kept.
   */
  heading: string;
  lead?: string | null;
  /**
   * Shown as a slow crossfade. Set the focal point on each image to control cropping.
   */
  images?: (number | Media)[] | null;
  showDonateButton?: boolean | null;
  /**
   * Optional second button.
   */
  secondaryLink?: {
    label?: string | null;
    /**
     * A path such as /about, a full URL, or a mailto: link.
     */
    href?: string | null;
  };
  /**
   * Optional. Counts down to the target time.
   */
  countdown?: {
    target?: string | null;
    label?: string | null;
    /**
     * Labels under the numbers.
     */
    units?: {
      days?: string | null;
      hours?: string | null;
      minutes?: string | null;
    };
  };
  /**
   * Figures shown in a band under the hero.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  layout: 'split' | 'prose';
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  text: string;
  source?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HostMapBlock".
 */
export interface HostMapBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * The extra line for online sessions.
   */
  onlineLabel?: string | null;
  /**
   * Shown beside the country that hosts the Anchor Day.
   */
  anchorLabel?: string | null;
  countries?:
    | {
        name: string;
        city?: string | null;
        /**
         * Position on the map grid, 0–932, left to right.
         */
        x: number;
        /**
         * Position on the map grid, 0–660, top to bottom.
         */
        y: number;
        labelSide: 'left' | 'right';
        anchor?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hostMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SummitWeekBlock".
 */
export interface SummitWeekBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * Shown under each date, e.g. Nov.
   */
  monthLabel?: string | null;
  days?:
    | {
        /**
         * Short name, e.g. Mon.
         */
        day: string;
        /**
         * Day of the month, e.g. 16.
         */
        date: string;
        label: string;
        body?: string | null;
        anchor?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'summitWeek';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoadmapBlock".
 */
export interface RoadmapBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * Number the steps instead of showing their timing.
   */
  numbered?: boolean | null;
  /**
   * The status line shown above each step.
   */
  statusLabels?: {
    done?: string | null;
    now?: string | null;
    next?: string | null;
  };
  steps?:
    | {
        when?: string | null;
        title: string;
        status: 'done' | 'now' | 'next';
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'roadmap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlowBlock".
 */
export interface FlowBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  steps?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  style: 'tiles' | 'badges';
  items?:
    | {
        icon:
          | 'megaphone'
          | 'shield'
          | 'stethoscope'
          | 'graduation'
          | 'landmark'
          | 'users'
          | 'video'
          | 'hand-heart'
          | 'file-text'
          | 'scale'
          | 'badge-check'
          | 'lock';
        /**
         * Optional for badges.
         */
        title?: string | null;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActionAreasBlock".
 */
export interface ActionAreasBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * Text in the middle of the wheel.
   */
  centreLabel?: string | null;
  areas?:
    | {
        icon:
          | 'megaphone'
          | 'shield'
          | 'stethoscope'
          | 'graduation'
          | 'landmark'
          | 'users'
          | 'video'
          | 'hand-heart'
          | 'file-text'
          | 'scale'
          | 'badge-check'
          | 'lock';
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional link under the wheel.
   */
  link?: {
    label?: string | null;
    /**
     * A path such as /about, a full URL, or a mailto: link.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'actionAreas';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupporterLevelsBlock".
 */
export interface SupporterLevelsBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  levels?:
    | {
        name: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'supporterLevels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoGridBlock".
 */
export interface LogoGridBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * Only entries with permission confirmed are shown.
   */
  source: 'supporters' | 'partners';
  /**
   * The banner scrolls once there are 5 or more logos; with fewer it shows them in a row. With none, the section is hidden.
   */
  display: 'grid' | 'marquee';
  /**
   * Shown when nobody can be listed yet.
   */
  emptyText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqListBlock".
 */
export interface FaqListBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * Show only FAQs in this category. Leave empty to show every FAQ.
   */
  category?: string | null;
  showCategories?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsTeaserBlock".
 */
export interface NewsTeaserBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  /**
   * For the News page: lists every item with its type, newest first.
   */
  showAll?: boolean | null;
  limit?: number | null;
  /**
   * Label for the link to /news.
   */
  linkLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DonateBannerBlock".
 */
export interface DonateBannerBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'donateBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  form: 'register-interest' | 'cta-consultation' | 'partner' | 'relay' | 'contact';
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnchorDayBlock".
 */
export interface AnchorDayBlock {
  /**
   * Small uppercase line above the heading.
   */
  kicker?: string | null;
  heading?: string | null;
  intro?: string | null;
  background: 'white' | 'pale' | 'blue';
  /**
   * Lets links jump to this section, e.g. "week" for /#week.
   */
  anchorId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'anchorDay';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Generated from the title when left empty.
   */
  slug: string;
  publishedDate: string;
  type: 'news' | 'partner-announcement';
  partner?: (number | null) | Partner;
  summary: string;
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Partner logos appear in logo grids and the scrolling partner banner once published with permission confirmed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * The organisation's full name. Screen readers read it out for the logo.
   */
  name: string;
  /**
   * A transparent PNG, SVG or WebP works best, around 480 pixels wide. Logos on a solid background should be on white.
   */
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * Optional. The full address, starting https://
   */
  website?: string | null;
  /**
   * Lower numbers come first. Partners without a number follow, A to Z.
   */
  order?: number | null;
  /**
   * The name and logo appear on the site only once the partner has given permission.
   */
  permissionConfirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supporters".
 */
export interface Supporter {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  level?: ('founding-regional' | 'regional' | 'access-participation' | 'community') | null;
  /**
   * The name and logo appear on the site only once the supporter has given permission.
   */
  permissionConfirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * FAQs with the same category are grouped together. An FAQ list block can filter by it.
   */
  category: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: 'register-interest' | 'cta-consultation' | 'partner' | 'relay' | 'contact';
  /**
   * The person's answers: name, email, phone and the form's own fields (SPEC §8.1, §8.3).
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  territory?: string | null;
  audienceType?: string | null;
  consents?: {
    contact?: boolean | null;
    publicName?: boolean | null;
    shareStory?: boolean | null;
  };
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  /**
   * Submitted before launch or from a non-production environment.
   */
  isTest?: boolean | null;
  airtableSyncStatus: 'pending' | 'synced' | 'failed';
  airtableSyncError?: string | null;
  airtableRecordId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'supporters';
        value: number | Supporter;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        hostMap?: T | HostMapBlockSelect<T>;
        summitWeek?: T | SummitWeekBlockSelect<T>;
        roadmap?: T | RoadmapBlockSelect<T>;
        flow?: T | FlowBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        actionAreas?: T | ActionAreasBlockSelect<T>;
        supporterLevels?: T | SupporterLevelsBlockSelect<T>;
        logoGrid?: T | LogoGridBlockSelect<T>;
        faqList?: T | FaqListBlockSelect<T>;
        newsTeaser?: T | NewsTeaserBlockSelect<T>;
        donateBanner?: T | DonateBannerBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        anchorDay?: T | AnchorDayBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  style?: T;
  kicker?: T;
  heading?: T;
  lead?: T;
  images?: T;
  showDonateButton?: T;
  secondaryLink?:
    | T
    | {
        label?: T;
        href?: T;
      };
  countdown?:
    | T
    | {
        target?: T;
        label?: T;
        units?:
          | T
          | {
              days?: T;
              hours?: T;
              minutes?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  content?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  text?: T;
  source?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HostMapBlock_select".
 */
export interface HostMapBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  onlineLabel?: T;
  anchorLabel?: T;
  countries?:
    | T
    | {
        name?: T;
        city?: T;
        x?: T;
        y?: T;
        labelSide?: T;
        anchor?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SummitWeekBlock_select".
 */
export interface SummitWeekBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  monthLabel?: T;
  days?:
    | T
    | {
        day?: T;
        date?: T;
        label?: T;
        body?: T;
        anchor?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoadmapBlock_select".
 */
export interface RoadmapBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  numbered?: T;
  statusLabels?:
    | T
    | {
        done?: T;
        now?: T;
        next?: T;
      };
  steps?:
    | T
    | {
        when?: T;
        title?: T;
        status?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlowBlock_select".
 */
export interface FlowBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  style?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActionAreasBlock_select".
 */
export interface ActionAreasBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  centreLabel?: T;
  areas?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  link?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupporterLevelsBlock_select".
 */
export interface SupporterLevelsBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  levels?:
    | T
    | {
        name?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoGridBlock_select".
 */
export interface LogoGridBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  source?: T;
  display?: T;
  emptyText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqListBlock_select".
 */
export interface FaqListBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  category?: T;
  showCategories?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsTeaserBlock_select".
 */
export interface NewsTeaserBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  showAll?: T;
  limit?: T;
  linkLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DonateBannerBlock_select".
 */
export interface DonateBannerBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnchorDayBlock_select".
 */
export interface AnchorDayBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  background?: T;
  anchorId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  type?: T;
  partner?: T;
  summary?: T;
  image?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  description?: T;
  website?: T;
  order?: T;
  permissionConfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supporters_select".
 */
export interface SupportersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  level?: T;
  permissionConfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  data?: T;
  territory?: T;
  audienceType?: T;
  consents?:
    | T
    | {
        contact?: T;
        publicName?: T;
        shareStory?: T;
      };
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  isTest?: T;
  airtableSyncStatus?: T;
  airtableSyncError?: T;
  airtableRecordId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Line breaks are kept.
   */
  brandTitle?: string | null;
  navItems?:
    | {
        label: string;
        /**
         * A path such as /about, a full URL, or a mailto: link.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The Donate button in the header.
   */
  donateLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The cookie settings link is added after these; its label is on Cookie Consent.
   */
  links?:
    | {
        label: string;
        /**
         * A path such as /about, a full URL, or a mailto: link.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  legalText?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-settings".
 */
export interface DonationSetting {
  id: number;
  suggestedAmounts?:
    | {
        /**
         * In cents: 2500 is $25.00.
         */
        amount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Three-letter ISO code in lower case, as Stripe expects.
   */
  currency?: string | null;
  allowCustomAmount?: boolean | null;
  /**
   * Smallest custom amount. In cents: 2500 is $25.00.
   */
  minimumAmount?: number | null;
  /**
   * Copy on /donate.
   */
  page?: {
    kicker?: string | null;
    heading?: string | null;
    lead?: string | null;
    reasonsHeading?: string | null;
    reasons?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
    amountLegend?: string | null;
    /**
     * The "Other" amount option.
     */
    otherLabel?: string | null;
    /**
     * Label on the custom amount input.
     */
    otherAmountLabel?: string | null;
    /**
     * Hint under the custom amount input. Use {minimum} for the minimum amount.
     */
    otherAmountHint?: string | null;
    submitLabel?: string | null;
    securePaymentNote?: string | null;
    /**
     * Shown when no valid amount is chosen. Use {minimum} for the minimum amount.
     */
    errorText?: string | null;
  };
  /**
   * The item donors see on Stripe's checkout page. Defaults to the site name.
   */
  checkoutItemName?: string | null;
  /**
   * Shown under the item name on the checkout page.
   */
  checkoutItemDescription?: string | null;
  /**
   * Line above the heading. Use {amount} for the amount given.
   */
  thankYouKicker?: string | null;
  thankYouHeading?: string | null;
  thankYouBody?: string | null;
  thankYouLinkLabel?: string | null;
  /**
   * Shown when Stripe has not confirmed the payment.
   */
  unconfirmedHeading?: string | null;
  unconfirmedBody?: string | null;
  unconfirmedLinkLabel?: string | null;
  /**
   * Copy shown by every Donate banner block.
   */
  banner?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Button label.
     */
    label?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every field is optional while the details are being confirmed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anchor-day".
 */
export interface AnchorDay {
  id: number;
  date?: string | null;
  venue?: string | null;
  moderator?: string | null;
  mc?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dropdowns".
 */
export interface Dropdown {
  id: number;
  territories?:
    | {
        label: string;
        /**
         * Stored on submissions and sent to Airtable. Avoid changing it once in use.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  audienceTypes?:
    | {
        label: string;
        /**
         * Stored on submissions and sent to Airtable. Avoid changing it once in use.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        label: string;
        /**
         * Stored on submissions and sent to Airtable. Avoid changing it once in use.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  /**
   * The site domain exactly as added in Plausible, for example amagisummit.org. Leave empty to turn analytics off.
   */
  plausibleDomain?: string | null;
  /**
   * For example GTM-ABC1234.
   */
  gtmContainerId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * One entry per form, shown on /thank-you/<form> after it is sent.
   */
  thankYou?:
    | {
        form: 'register-interest' | 'cta-consultation' | 'partner' | 'relay' | 'contact';
        heading: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consent".
 */
export interface CookieConsent {
  id: number;
  heading?: string | null;
  body?: string | null;
  acceptLabel?: string | null;
  rejectLabel?: string | null;
  /**
   * The footer link that reopens the cookie banner.
   */
  settingsLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon".
 */
export interface ComingSoon {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Line breaks are kept.
   */
  brandTitle?: string | null;
  /**
   * Small uppercase line above the headline.
   */
  kicker?: string | null;
  /**
   * Line breaks are kept.
   */
  headline: string;
  lead?: string | null;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * The QR code is generated from this link.
     */
    url?: string | null;
  };
  qr?: {
    label?: string | null;
    sublabel?: string | null;
  };
  details?:
    | {
        icon?: ('calendar' | 'map-pin' | 'globe' | 'users' | 'clock' | 'mail') | null;
        title: string;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as a slow crossfade, 8 seconds each. Set the focal point on each image to control cropping.
   */
  backgroundImages?: (number | Media)[] | null;
  footerLeft?: string | null;
  footerRight?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  brandTitle?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  donateLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  tagline?: T;
  legalText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-settings_select".
 */
export interface DonationSettingsSelect<T extends boolean = true> {
  suggestedAmounts?:
    | T
    | {
        amount?: T;
        id?: T;
      };
  currency?: T;
  allowCustomAmount?: T;
  minimumAmount?: T;
  page?:
    | T
    | {
        kicker?: T;
        heading?: T;
        lead?: T;
        reasonsHeading?: T;
        reasons?:
          | T
          | {
              text?: T;
              id?: T;
            };
        note?: T;
        amountLegend?: T;
        otherLabel?: T;
        otherAmountLabel?: T;
        otherAmountHint?: T;
        submitLabel?: T;
        securePaymentNote?: T;
        errorText?: T;
      };
  checkoutItemName?: T;
  checkoutItemDescription?: T;
  thankYouKicker?: T;
  thankYouHeading?: T;
  thankYouBody?: T;
  thankYouLinkLabel?: T;
  unconfirmedHeading?: T;
  unconfirmedBody?: T;
  unconfirmedLinkLabel?: T;
  banner?:
    | T
    | {
        heading?: T;
        body?: T;
        label?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anchor-day_select".
 */
export interface AnchorDaySelect<T extends boolean = true> {
  date?: T;
  venue?: T;
  moderator?: T;
  mc?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dropdowns_select".
 */
export interface DropdownsSelect<T extends boolean = true> {
  territories?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  audienceTypes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  plausibleDomain?: T;
  gtmContainerId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  thankYou?:
    | T
    | {
        form?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consent_select".
 */
export interface CookieConsentSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  acceptLabel?: T;
  rejectLabel?: T;
  settingsLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon_select".
 */
export interface ComingSoonSelect<T extends boolean = true> {
  logo?: T;
  brandTitle?: T;
  kicker?: T;
  headline?: T;
  lead?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  qr?:
    | T
    | {
        label?: T;
        sublabel?: T;
      };
  details?:
    | T
    | {
        icon?: T;
        title?: T;
        subtitle?: T;
        id?: T;
      };
  backgroundImages?: T;
  footerLeft?: T;
  footerRight?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}